name: Demo_github_project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    

